"""Initial migration

Revision ID: 1bf1ad37a3c5
Revises: 
Create Date: 2026-03-27 19:13:03.256534

"""
from alembic import op
import sqlalchemy as sa

from portal.models.base import UTCDateTime

# revision identifiers, used by Alembic.
revision = '1bf1ad37a3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expiry', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_key'), ['key'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_flow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('flow_token_hash', sa.String(), nullable=False),
    sa.Column('email_otp_hash', sa.String(), nullable=True),
    sa.Column('email_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('expiry', UTCDateTime(), nullable=False),
    sa.Column('email_verified', UTCDateTime(), nullable=True),
    sa.Column('totp_verified', UTCDateTime(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('ip_rate_limit_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_role',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'role_id')
    )
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created', UTCDateTime(), nullable=False),
    sa.Column('last_active', UTCDateTime(), nullable=False),
    sa.Column('last_auth', UTCDateTime(), nullable=False),
    sa.Column('last_email_auth', UTCDateTime(), nullable=True),
    sa.Column('last_keyfob_auth', UTCDateTime(), nullable=True),
    sa.Column('last_totp_auth', UTCDateTime(), nullable=True),
    sa.Column('last_passkey_auth', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('member_role')
    op.drop_table('auth_flow')
    op.drop_table('role')
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_key'))

    op.drop_table('rate_limit')
    op.drop_table('member')
    op.drop_table('app')
    # ### end Alembic commands ###
