"""Record active clients per session

Revision ID: 5fed490073bc
Revises: a68ac3234eba
Create Date: 2026-04-22 09:13:06.858277

"""

from alembic import op
import sqlalchemy as sa
from portal.models.base import SpaceSeparatedSet

# revision identifiers, used by Alembic.
revision = "5fed490073bc"
down_revision = "a68ac3234eba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "active_clients",
                SpaceSeparatedSet(),
                server_default="",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_column("active_clients")

    # ### end Alembic commands ###
