"""Add join/leave columns

Revision ID: 7be575704f06
Revises: df10a1b76238
Create Date: 2026-04-06 14:34:02.629282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be575704f06'
down_revision = 'df10a1b76238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leave_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('leave_date')
        batch_op.drop_column('join_date')

    # ### end Alembic commands ###
