"""Audit Log table

Revision ID: a68ac3234eba
Revises: cd892fa296b8
Create Date: 2026-04-20 12:44:07.016171

"""

from alembic import op
import sqlalchemy as sa
from portal.models.base import UTCDateTime

# revision identifiers, used by Alembic.
revision = "a68ac3234eba"
down_revision = "cd892fa296b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("logged_at", UTCDateTime(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_logged_at", ["logged_at"], unique=False, postgresql_using="brin"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_logged_at", postgresql_using="brin")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
