"""Add updated column

Revision ID: df10a1b76238
Revises: e02fc5b17612
Create Date: 2026-04-06 14:25:50.407856

"""

from alembic import op
import sqlalchemy as sa

from portal.models.base import UTCDateTime

# revision identifiers, used by Alembic.
revision = "df10a1b76238"
down_revision = "e02fc5b17612"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated", UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.drop_column("updated")

    # ### end Alembic commands ###
