"""Add role claims

Revision ID: e02fc5b17612
Revises: 1bf1ad37a3c5
Create Date: 2026-03-29 18:28:41.157204

"""
from alembic import op
import sqlalchemy as sa

from portal.models.base import SpaceSeparatedSet


# revision identifiers, used by Alembic.
revision = 'e02fc5b17612'
down_revision = '1bf1ad37a3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claims', SpaceSeparatedSet(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('claims')

    # ### end Alembic commands ###
